/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package figurecollectionv1;

import com.quesada.figures.Main;
import org.junit.Test;

public class LibraryTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        Main.main(new String[]{});
    }
}
